### PR TITLE
Changed the baseurl to the right location

### PR DESCRIPTION
**Pull request by rikatz**
Changed the baseurl from the yum repository to the right location

### CODE REVIEW

**Comment by rikatz** [comment]
Correcting the wrong location of the baseurl

**Comment by bernd** [comment]
The current location is actually correct. What problem does this change fix for you?

**Comment by rikatz** [comment]
Hi @bernd , it isn't :(

See, the change that I made was on the file that generates the /etc/yum.repos.d/graylog.repo.

Originally, it points to https://packages.graylog2.org/repo/el/stable/2.0/x86_64 but this directory doesn't exist.

The correct directory (surfing on the packages.graylog2.org) is https://packages.graylog2.org/el/stable/2.0/x86_64

Also, it says that the repomd.xml (when pointing to the correct location) is corrupted :)

Thanks

**Comment by bernd** [comment]
> The correct directory (surfing on the packages.graylog2.org) is

The `/repo` location is a different one than the one you see with the browser. Please try using yum with the original `/repo` location. That should work.

**Comment by rikatz** [comment]
@bernd You're right! Probably I've missed a yum clean all before upgrading everything, and while looking for the solution I've faced this as a wrong directory (although I'm wrong).

Sorry about that, thanks!!

**Comment by bernd** [comment]
No worries, glad it's working for you now! :smiley:

**Pull request closed without merging**
