### PR TITLE
Enable ARM64 builds for Sidecar and ship collectors in OS packages

### PR DESCRIPTION
**Pull request by bernd**

### CODE REVIEW

**Comment by mpfz0r** [comment]
I'm confused. Since when do we have another package build here?

Why didn't we retire this one then?
https://github.com/Graylog2/collector-sidecar/blob/master/dist/recipe.rb

**Comment by mpfz0r** [comment]
Also, what's the benefit of duplicating this into two repositories?

**Comment by bernd** [comment]
> I'm confused. Since when do we have another package build here?
> 
> Why didn't we retire this one then? https://github.com/Graylog2/collector-sidecar/blob/master/dist/recipe.rb

I don't know why the build infrastructure in the Sidecar GitHub repository wasn't removed. I think because we don't build all the legacy operating system packages for our official package repos and wanted to still offer them for download on the Sidecar GitHub releases page.

The infrastructure in this repo builds the official packages for our operating system package repository.

**Comment by mpfz0r** [comment]
> The infrastructure in this repo builds the official packages for our operating system package repository.

Couldn't we have kept this in a single repo?
Now we have to maintain two copies of the sidecar.yml

**Comment by bernd** [comment]
> > The infrastructure in this repo builds the official packages for our operating system package repository.
> 
> Couldn't we have kept this in a single repo? Now we have to maintain two copies of the sidecar.yml

If we want to be able to release a new package revision without releasing a new Sidecar version, then we have to have a way of customizing the config file. In the Server, we use patches for that. We can probably do the same here.

**Review by mpfz0r — APPROVED** [review]

**Pull request merged**
